
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadoresLexicoSintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EXEC = 16;
  public static final int TIPO_VARIABLE = 3;
  public static final int MENOS = 5;
  public static final int CADENA = 21;
  public static final int IGUAL = 9;
  public static final int EXPRESION_ARRAY = 25;
  public static final int DECIMAL = 23;
  public static final int COLUMN = 18;
  public static final int PARENTESIS_IZQUIERDO = 13;
  public static final int ARITMETICA = 29;
  public static final int CORCHETE_DERECHO = 12;
  public static final int END = 4;
  public static final int CONSOLE = 19;
  public static final int CORCHETE_IZQUIERDO = 11;
  public static final int MAYOR_QUE = 10;
  public static final int TITULO_EJE = 31;
  public static final int ESTADISTICA = 30;
  public static final int PROGRAM = 27;
  public static final int PARENTESIS_DERECHO = 14;
  public static final int DOS_PUNTOS = 6;
  public static final int COMA = 15;
  public static final int MENOR_QUE = 7;
  public static final int EOF = 0;
  public static final int VALUES = 33;
  public static final int END_PROGRAM = 28;
  public static final int PRINT = 17;
  public static final int error = 1;
  public static final int TIPO_GRAFICA = 20;
  public static final int PUNTO_COMA = 8;
  public static final int ENTERO = 22;
  public static final int TITULO_GRAFICA = 34;
  public static final int ARRAY = 26;
  public static final int LABEL = 32;
  public static final int EXPRESION = 24;
  public static final int VAR = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VAR",
  "TIPO_VARIABLE",
  "END",
  "MENOS",
  "DOS_PUNTOS",
  "MENOR_QUE",
  "PUNTO_COMA",
  "IGUAL",
  "MAYOR_QUE",
  "CORCHETE_IZQUIERDO",
  "CORCHETE_DERECHO",
  "PARENTESIS_IZQUIERDO",
  "PARENTESIS_DERECHO",
  "COMA",
  "EXEC",
  "PRINT",
  "COLUMN",
  "CONSOLE",
  "TIPO_GRAFICA",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "EXPRESION",
  "EXPRESION_ARRAY",
  "ARRAY",
  "PROGRAM",
  "END_PROGRAM",
  "ARITMETICA",
  "ESTADISTICA",
  "TITULO_EJE",
  "LABEL",
  "VALUES",
  "TITULO_GRAFICA"
  };
}

